
#==================FuelShineUma=====================
HomePage = 
VerifyErrorMsg =
ValidMobileNumber = 9000961659
ValidMobileNumber2 = 6303429063
ValidOTP = 234466
ValidateHomePage = 
VerifyOtpErrorMsg =
#==================== Mobile Configs================================

CustomDeviceName=MyBullet
#AppLocation = /src/test/resources/MobileApps/app-release.apk
#mobile=6303429063
#otp=234466
ShareFeedBackInfo=Trip feedback
MyVehiRegNumber=KA01MV8994
EmptyVehiRegNumber=
Service_Reminder_in_KMs=abcd
Gypsee_odometerReading=defv
carName = HYUNDAI MOTOR
##==================Web Configs===========================
#
#
#Url = 
#email = 
#pass = 
#
#
##========================API Configs==================================
#baseURI= https://gypsee.in/gypsee


AppLocation = /src/test/resources/MobileApps/app-release.apk

mobile=6303429063
otp=234466
#mobile=9000961659



#==================Uma==========================
registrationNumber = AP39AJ8284
errorMsg = You have already reached maximum limit
updateProfileValidation = Update vehicle details
serviceRemainder2 = kilometers
HomeScreen = Home
odometerReading = car

#=====================priya===============

internetConMsg = Please Check your internet connection
connect = Connect
execType=Mobile_UI
MobileNumber2=6303429063
OTP=234466
otpHdr = OTP Verification
home = Home
txt = Please enter your mobile number to drive safe
chhoseAnAccount = Choose an account
Name=Testing
City=Hyderabad
EmailID=test123@gmail.com
MobileNo=6789034567
EnterSubscription=23456
EnterCode=345678
SafetyCenter = Safety Center
accident = Accident
preSerAsst = Preferred service assistance
vehBrkdwn = Vehicle Breakdown
Roadrage = Road Rage
confirmation = Confirmation
readyassit = ReadyAssist
members = Members
howitworks = How it Works
emerdir = Emergency Directory
emerSer = Emergency Services
howdoesitwork = How does it Works?
step1 = Step 1: Emergency situation
step2 = Step 2: Press SOS
step3 = Step 3: Shared Location with Type of Emergency
emerCon = Emergency Contact
perReq = Permission Request!
AddMemErrMsg = Please enter valid inputs
#==================Web Configs===========================


Url = 
email = 
pass = 


#========================API Configs==================================
baseURI= https://gypsee.in/gypsee


#==============================Gypsee00=====================================
MobileNumber = 6789034567
EnterSubscription = rented
EnterCode =09876
